services:
  dev:
    container_name: SudokuSolverDevtainer
    image: sudokusolver:dev
    build: .
    volumes:
      - ./cmd:/app/cmd
      - ./sudoku:/app/sudoku
      - ./.air.toml:/app/.air.toml
      - ./Makefile:/app/Makefile
    command: tail -f /dev/null
